rabbitmq:
  username  : xxxx
  password  : xxxx

twitter:
  consumer_key        : xxxxxxxxxxxxxxxxxxxxx
  consumer_secret     : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  access_token        : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  access_token_secret : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
