version : 1
disable_existing_loggers: False
formatters:
  categories:
    format: "%(firstName) -15s %(serviceName) -15s %(className) -20s %(instanceName) -20s %(levelname) -10s %(message)s"
  rich:
    format: "%(asctime)s  %(name) -30s %(className) -20s %(lineno) 5d %(funcName) -20s %(levelname) -10s %(message)s"
  compact:
    format: "%(name) -30s %(levelname) -10s %(message)s"

handlers:
  console:
    class       : logging.StreamHandler
    formatter   : rich
    level       : TRACE
    stream      : ext://sys.stdout
loggers:
  "":
    handlers    : [console]
    level       : WARNING
  servicelog:
    level       : DEBUG
  proclog:
    level       : DEBUG
  doclog:
    level       : WARNING
